### ISSUE TITLE
Add basic documentation

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-cloud#11]
- [x] https://github.com/eclipsesource/theia-cloud-website/issues/16
- [x] https://github.com/eclipsesource/theia-cloud-website/issues/17
- [x] https://github.com/eclipsesource/theia-cloud-website/issues/18
- [ ] https://github.com/eclipsesource/theia-cloud-website/issues/19
- [x] https://github.com/eclipsesource/theia-cloud-website/issues/20
- [x] https://github.com/eclipsesource/theia-cloud-website/issues/21
- [x] https://github.com/eclipsesource/theia-cloud-website/issues/22

**Comment by jfaltermeier** [comment]
Keep open

**Comment by jfaltermeier** [comment]
Keep open

**Comment by jfaltermeier** [comment]
Keep open

**Comment by jfaltermeier** [comment]
Keep open

**Comment by jfaltermeier** [comment]
I've added the topics we work on next in the description

**Comment by jfaltermeier** [comment]
Closing this umrella ticket as only one subticket is still open.
