### ISSUE TITLE
Add possibility to define custom ENV vars in helm charts

### ISSUE THREAD

**Issue by mclay** [eclipse-theia/theia-cloud#148]
Requirement: pass additional ENV vars to the IDE container

I will provide a PR for this.

**Comment by jfaltermeier** [comment]
Thanks, let us know if there are any questions.

**Comment by lucas-koehler** [comment]
@mclay In case you are still working on this, note that there is an open pr now that might implement this issue: #156

**Comment by askarbozcan** [comment]
I had 2 ideas regarding that:

1. Using templating to insert envvars from chart values into a 'singleton' config map (maybe something like theia-template-envvar-cm), and then simply passing this cm ref as just another configMapRef to Deployment (thankfully, one of the util functions in this PR is exactly for doing that). 

2. Adding env vars from chart as arguments to operator, and again using one of util functions from #156 to add the env vars.

Both should work for Eager as well, as the env vars are known in advance.


What do you think?

**Comment by mclay** [comment]
hi, no problem you could work on this and take over the issue. To be honest I came to the conclusion that the whole templating or variable substitution (not only env-vars, everything) should be done outside of the code. The reasons for that in my opinion are

- the current approach is to static: every time a new use cases requires it you have to change the source code (e.g. env var)
- there are already established tools that do this job and the community is used to it e.g. helm, tf, etc

Therefore I would suggest to refactor this and move all of the templating outside of the code by leveraging an existing approach/tool in this area. e.g. the appdefinition could point to a helm chart and a configmap that is automatically provisioned. There exists a helm sdk in go for that.
