### ISSUE TITLE
Contribute to Theia at Eclipse Foundation

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-cloud#31]

**Comment by jfaltermeier** [comment]
Keep open

**Comment by jfaltermeier** [comment]
Keep open

**Comment by jfaltermeier** [comment]
Keep open

**Comment by jfaltermeier** [comment]
Keep open

**Comment by jfaltermeier** [comment]
Tickets:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4910
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15954
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15953
