### ISSUE TITLE
Rename Theia Blueprint App Image to Theia IDE

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-cloud#355]
### Describe the bug

Theia Blueprint is not existing anymore. Got a user report that was confused, it is visible here in the drop down: https://try.theia-cloud.io/

### Expected behavior

Theia IDE inseatd of Blueprint

**Comment by koegel** [comment]
While we are at it, we should also align the other entries in the menu:

- Theia IDE
- CDT Cloud Blueprint
- EMF Cloud Coffee Editor
